### ISSUE TITLE
Document container background cuts off on scroll on mobile devices 

### ISSUE THREAD

**Issue by deansheather** [TheCrossroads/discord-guides#14]
When the page breakpoints decide to "dock" the content container to the viewport, the background of the background container cuts off on page scroll. I suspect this has something to do with the height being set on the container manually, but have yet to check and confirm this. 

### Screenshot
![screenshot_20160808-215032](https://cloud.githubusercontent.com/assets/11241812/17478910/6c6135be-5db2-11e6-9997-dd4d7982ae47.png)

**Comment by Zeludon** [comment]
#16
